sudo: false
language: python
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/oc
python:
  - "3.6"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
before_script:
  - psql -U postgres -c 'CREATE DATABASE "oc";'
script:
  - coverage run manage.py test --settings=settings.test
after_success:
  - codecov
