[bumpver]
current_version = "2023.1.1"
version_pattern = "YYYY.MM.INC1"
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
commit = true
push = false  # disabled for GitHub Actions
tag = true

[bumpver.file_patterns]
"core/__init__.py" = [
    '__version__ = "{version}"',
]
# "bumpver.toml" = [
#     'current_version = "{version}"',
# ]
